// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package models

import (
	"encoding/json"
	"time"
)

type ProductDetail struct {
	ID        int64     `json:"id"`
	CreateAt  time.Time `json:"create_at"`
	UpdateAt  time.Time `json:"update_at"`
	ProductID int64     `json:"product_id"`
	Color     string    `json:"color"`
	SizeOs    int32     `json:"size_os"`
	SizeS     int32     `json:"size_s"`
	SizeM     int32     `json:"size_m"`
	SizeL     int32     `json:"size_l"`
	SizeXl    int32     `json:"size_xl"`
}

type ProductList struct {
	ID                 int64           `json:"id"`
	CreateAt           time.Time       `json:"create_at"`
	UpdateAt           time.Time       `json:"update_at"`
	ProductName        string          `json:"product_name"`
	ProductDescription string          `json:"product_description"`
	ProductMarketPrice int32           `json:"product_market_price"`
	ProductSalePrice   int32           `json:"product_sale_price"`
	ProductTags        json.RawMessage `json:"product_tags"`
	Pictures           json.RawMessage `json:"pictures"`
	Colors             json.RawMessage `json:"colors"`
}
